package:
  name: xonsh
  version: {{ environ.get('GIT_DESCRIBE_TAG', '0.0.0') }}

source:
   git_url: ../

build:
  script: python setup.py install --single-version-externally-managed --record=record.txt
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  skip: True  # [py2k]
  entry_points:
    - xonsh = xonsh.main:main

requirements:
  build:
    - python
    - setuptools
    - jupyter
  run:
    - python
    - prompt_toolkit
    - setproctitle
    - pygments

app:
  entry: xonsh
  icon: ../docs/_static/ascii_conch_part_color.png

about:
  home: http://xon.sh/
  license: BSD
  summary: xonsh is a Python-ish, BASHwards-facing shell.

