package:
  name: xonsh
  version: "0.2.6"

source:
   path: ../

build:
  number: 0
  entry_points:
    - xonsh = xonsh.main:main

requirements:
  build:
    - python
    - ply
    - setuptools
    - jupyter
  run:
    - python
    - ply
    - pygments
    - prompt_toolkit
    - setproctitle

about:
  home: http://xon.sh/
  license: BSD
  summary: xonsh is a Python-ish, BASHwards-facing shell.

# Removed temporarily until this is better support by the Anaconda launcher
#app:
#  entry: xonsh
#  icon: icon.png
