version: 0.6.0.{build}
os: Windows Server 2012 R2
environment:

  matrix:
    # http://www.appveyor.com/docs/installed-software#python
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python34-x64"
      DISTUTILS_USE_SDK: "1"
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36-x64"
    - XONSH_TEST_ENV: "MSYS2"
      MSYS2_PATH: "C:\\msys64"
    # TODO: Miniconda
install:
  - ".appveyor_install.cmd"
build: off
test_script:
  - ".appveyor_test.cmd"
