machine:
    environment:
        PATH: /home/ubuntu/miniconda/envs/test_env/bin:/home/ubuntu/miniconda/bin:$PATH
    post:
        - pyenv global 3.4.4 3.5.1

dependencies:
    pre:
        - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
        - bash miniconda.sh -b -p $HOME/miniconda
        - conda config --set always_yes yes --set changeps1 no
        - conda update -q conda
        - ./.circle_miniconda.sh
        - rm -rf ~/.pyenv
        - rm -rf ~/virtualenvs
    post:
        - python setup.py install

test:
    override:
        - py.test --timeout=10
