doc-warnings: yes
test-warnings: yes
strictness: veryhigh
max-line-length: 100
autodetect: yes
ignore-paths:
    - docs/conf.py

pylint:
  disable:
    - syntax-error  # have to do this since landscape doesn't support py3k
    - super-on-old-class
    - global-variable-not-assigned
    - pointless-except
    - unused-argument
    - protected-access
    - global-statement

mccabe:
  disable:
    - MC0000  # again, not Py3k compatabile
