doc-warnings: yes
test-warnings: yes
strictness: veryhigh
max-line-length: 90
autodetect: yes
ignore-paths:
    - docs/conf.py
    - xonsh/ply

python-targets:
    - 3
         
pylint:
  disable:
    - super-on-old-class
    - old-style-class
    - global-variable-not-assigned
    - pointless-except
    - unused-argument
    - protected-access
    - global-statement
    - eval-used
    - exec-used
    - too-many-lines
    - import-self
    - redefined-outer-name
    - invalid-name
    - too-few-public-methods
    - no-init
    - star-args

mccabe:
  disable:
    - MC0000  # not Py3k compatabile
    - MC0001  # silly cyclomatic complexity
