language: python

matrix:
    include:
        - os: linux
          python: "nightly"
          env: TOXENV=py36
        - os: linux
          python: 3.5
          env: TOXENV=py35
        - os: linux
          python: 3.4
          env: TOXENV=py34
        - os: osx
          language: generic
          env: TOXENV=py35
        - os: osx
          language: generic
          env: TOXENV=py34
install:
    - ./install.sh
script:
  - python3 -m coverage run --source xonsh -m py.test -v --timeout=10 tests/
after_success:
  - codecov
