language: python
python:
  - 3.4
  - 3.5
  - "nightly"
env:
  - XONSH_DEBUG=1
install:
  - pip install --upgrade -r requirements-tests.txt
script:
  - python setup.py develop
  - XONSH_DEBUG=1 py.test --flake8 --cov=. --cov-report=term
after_success:
  - codecov
